using System;
using System.IO;
using DokiDex.Control.Services;
using Xunit;

namespace DokiDex.Control.Tests;

// The GPU-free parts of the Studio's live path: the output-artifact factory, doki's error-line surfacing, and
// the security scoping on OpenLocalMedia (the actual gen run needs the card and is smoke-checked there).
public class DokiServiceGenTests
{
    [Theory]
    [InlineData("image", ".png")]
    [InlineData("video", ".mp4")]
    [InlineData("music", ".mp3")]
    public void NewGenOutPath_is_a_scoped_fully_qualified_path_in_the_output_dir(string kind, string ext)
    {
        // drive the overridable resolver so the test is deterministic and independent of where the exe lives.
        var testDir = Path.Combine(Path.GetTempPath(), "dokigen-test");
        var prev = DokiService.GenDirResolver;
        DokiService.GenDirResolver = () => testDir;
        try
        {
            var p = new DokiService().NewGenOutPath(kind);
            Assert.True(Path.IsPathFullyQualified(p));
            Assert.Equal(ext, Path.GetExtension(p));
            Assert.StartsWith(Path.GetFullPath(testDir), Path.GetFullPath(p), StringComparison.OrdinalIgnoreCase);
        }
        finally { DokiService.GenDirResolver = prev; }
    }

    [Fact]
    public void NewGenOutPath_is_unique_per_call()
        => Assert.NotEqual(new DokiService().NewGenOutPath("image"), new DokiService().NewGenOutPath("image"));

    [Fact]
    public void LastMeaningfulLine_returns_last_nonblank_trimmed()
    {
        Assert.Equal("boom", DokiService.LastMeaningfulLine("one\ntwo\n  boom  \n\n"));
        Assert.Null(DokiService.LastMeaningfulLine("   \n  \n"));
        Assert.Null(DokiService.LastMeaningfulLine(null));
    }

    // OpenLocalMedia must shell-open ONLY a real media file the panel itself generated (a path returned by
    // NewGenOutPath). Every out-of-contract input has to no-op silently (and never launch) — we assert it
    // doesn't throw; the early returns happen before any Process.Start, so a passing call = nothing launched.
    [Fact]
    public void OpenLocalMedia_rejects_out_of_contract_paths_without_throwing()
    {
        var svc = new DokiService();
        var scratch = Path.Combine(Path.GetTempPath(), "dokigen-test");
        svc.OpenLocalMedia("");                                  // empty
        svc.OpenLocalMedia("relative\\x.png");                   // not fully-qualified
        svc.OpenLocalMedia(@"C:\Windows\System32\calc.exe");     // not a path the panel generated (and not media)
        svc.OpenLocalMedia(Path.Combine(scratch, "nope.png"));   // never generated by us + doesn't exist
        svc.OpenLocalMedia(Path.Combine(scratch, "evil.exe"));   // never generated + disallowed ext
        svc.OpenLocalMedia(Path.Combine(scratch, @"..\..\Windows\System32\calc.exe")); // traversal, not ours
        Assert.True(true);   // reaching here = no launch, no throw
    }
}
