using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using DokiDex.Control.Services;

namespace DokiDex.Web;

// A NAMED, cross-conversation KNOWLEDGE-BASE library: a workspace you build once (drop docs in) and attach to ANY
// chat — the AnythingLLM pattern, the promotion the per-conversation KB header (ChatStore.cs) anticipated. ADDITIVE
// over the v0.14/v0.15 doc pipeline: a KbRecord.Id is just an opaque kb_id to doc_index.py, so a named KB's docs are
// ingested/searched/removed through the EXISTING DocSearch methods, ZERO change to doc_index.py / DocSearch.cs / Chat.cs.
//
// Like ChatStore (and unlike personas/lorebooks/recipes) the FILE STEM is a SERVER-generated id, NOT a user filename:
// so two KBs can share a display Name, a rename can't move chunks, and there is no client path => no traversal surface.
// The "kb-" prefix makes a named-KB id visually distinct from a conversation id (timestamp-only) inside doc_index.db
// and is harmless to SafeName / the python (all kb- chars are SafeName-legal).
public sealed record KbRecord(string Id, string Name, string Created);

// POST /api/kbs body: just the display name (the id + created stamp are server-generated by NewKb).
public sealed record KbCreateRequest(string? Name);

// POST /api/chats/{id}/kb body: the named KB id to attach (a kb-* id); "" / null detaches back to per-conversation.
public sealed record ChatKbRequest(string? KbId);

// Named-KB registry — file-based under <home>/kbs/<id>.json, a direct clone of ChatStore's id-keyed variant
// (server-generated id, SafeName-guarded Load/Delete, graceful try/catch). List orders by Name (the display order).
public static class KbStore
{
    private static string Dir => Path.Combine(RepoPaths.Root, "kbs");

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    // A fresh named KB with a server-generated, traversal-free id (kb- + timestamp + short guid, all SafeName-legal).
    // The id is what becomes the doc_index kb_id for this library's docs — distinct from a conversation id so the two
    // never collide in doc_index.db.
    public static KbRecord NewKb(string? name)
        => new(
            Id: $"kb-{DateTime.UtcNow:yyyyMMdd-HHmmss}-{Guid.NewGuid().ToString("N")[..8]}",
            Name: (name ?? "").Trim(),
            Created: DateTime.UtcNow.ToString("o"));

    public static IReadOnlyList<KbRecord> List()
    {
        if (!Directory.Exists(Dir)) return Array.Empty<KbRecord>();
        var outp = new List<KbRecord>();
        foreach (var f in Directory.EnumerateFiles(Dir, "*.json"))
            try
            {
                var k = JsonSerializer.Deserialize<KbRecord>(File.ReadAllText(f), JsonOpts);
                if (k is not null && !string.IsNullOrWhiteSpace(k.Id)) outp.Add(k);
            }
            catch { }
        return outp.OrderBy(k => k.Name, StringComparer.OrdinalIgnoreCase).ToList();
    }

    public static KbRecord? Load(string? id)
    {
        var n = RecipeStore.SafeName(id);
        if (n is null) return null;
        var p = Path.Combine(Dir, n + ".json");
        try { return File.Exists(p) ? JsonSerializer.Deserialize<KbRecord>(File.ReadAllText(p), JsonOpts) : null; }
        catch { return null; }
    }

    public static bool Save(KbRecord? rec)
    {
        var n = RecipeStore.SafeName(rec?.Id);
        if (n is null) return false;
        try { Directory.CreateDirectory(Dir); File.WriteAllText(Path.Combine(Dir, n + ".json"), JsonSerializer.Serialize(rec)); return true; }
        catch { return false; }
    }

    public static bool Delete(string? id)
    {
        var n = RecipeStore.SafeName(id);
        if (n is null) return false;
        var p = Path.Combine(Dir, n + ".json");
        try { if (File.Exists(p)) File.Delete(p); return true; }
        catch { return false; }
    }

    // The attach RESOLUTION (a pure helper) — a conversation -> its effective kb_id:
    //   • KbId set (a NAMED library id, OR — as today — the conversation's own id after a private-doc attach) -> that id
    //   • KbId blank/null (a fresh thread, no attached docs) -> the conversation's OWN id (the per-conversation scope)
    // Both branches yield a plain kb_id string.
    //
    // NOTE on the retrieval path: the Chat.cs send paths (SendAsync/AgentAsync/StreamAsync) do NOT route through this
    // helper — they pass the RAW conv.KbId to RetrieveDocs, where a null/blank KbId short-circuits to no injection so
    // the no-KB chat path stays byte-for-byte. EffectiveKbId / ScopeToCleanupOnConversationDelete are used by the
    // DELETE/cleanup site only (resolving which doc_index scope a conversation owns), NOT by retrieval.
    public static string EffectiveKbId(Conversation c)
        => string.IsNullOrWhiteSpace(c.KbId) ? c.Id : c.KbId!;

    // The conversation-delete CLEANUP scope (the disk-leak fix) — a conversation -> the doc_index kb_id that DELETE
    // /api/chats/{id} must drop, best-effort. It is ALWAYS the conversation's OWN private per-conversation scope
    // (conv.Id, where any privately-ingested chunks live), regardless of whether the thread was later pointed at a
    // NAMED library. A shared named (kb-*) library is DELIBERATELY never returned here: other threads may still use
    // it, so it is dropped only by DELETE /api/kbs/{id}. This is the rule that closes the
    // private->named->delete orphan leak (a named-attached thread's private chunks were previously skipped).
    public static string ScopeToCleanupOnConversationDelete(Conversation c) => c.Id;

    // Detach-to-private RESOLUTION (POST /api/chats/{id}/kb with a blank kbId) — what KbId to store when a thread is
    // detached from a named library:
    //   • the conversation has private docs under conv.Id -> conv.Id (RESTORE its own KB so those docs are actually
    //     RETRIEVED, not merely listed — null here would leave the pill saying "private" while RetrieveDocs(null)
    //     short-circuits, i.e. "RAG looks on but is off")
    //   • no private docs -> null (the clean no-KB state: retrieval short-circuits, plain chat resumes byte-for-byte)
    // hasPrivateDocs is supplied by the endpoint (a DocSearch.SourcesAsync(conv.Id) non-empty check) so this decision
    // stays a pure, unit-testable function with no process/disk dependency.
    public static string? ResolveDetachKbId(Conversation c, bool hasPrivateDocs)
        => hasPrivateDocs ? c.Id : null;
}
